#version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: codrr_pg
    # restart: always
    environment:
      POSTGRES_DB: codrrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

